version: "3.2"

services:

  tc-server: ### the main tc-server (aka SUT)
    image: jetbrains/teamcity-server
    container_name: teamcity-server-instance
    ports:
      - "8111:8111"
    networks:
      jbrs_net:
        ipv4_address: 10.5.0.5
    volumes:
      - ./teamcity_server/datadir:/data/teamcity_server/datadir
      - ./teamcity_server/logs:/opt/teamcity/logs

  agent1: ### this agent exists as authorized one
    image: jetbrains/teamcity-agent
    privileged: true
    container_name: teamcity-agent1-instance
    volumes:
      - ./teamcity_agent/agent1/conf:/data/teamcity_agent/conf
    networks:
      jbrs_net:
        ipv4_address: 10.5.0.6
    depends_on:
      - tc-server
    environment:
      - SERVER_URL=tc-server:8111
      - AGENT_NAME=teamcity-agent1
      - DOCKER_IN_DOCKER=start

  agent2: ### this agent exists as unauthorized one
    image: jetbrains/teamcity-agent
    privileged: true
    container_name: teamcity-agent2-instance
    volumes:
      - ./teamcity_agent/agent2/conf:/data/teamcity_agent/conf
    networks:
      jbrs_net:
        ipv4_address: 10.5.0.7
    depends_on:
      - tc-server
    environment:
      - SERVER_URL=tc-server:8111
      - AGENT_NAME=teamcity-agent2
      - DOCKER_IN_DOCKER=start
  selenoid:
    image: "aerokube/selenoid:latest"
    container_name: selenoid
    ports:
      - "4445:4444"
    networks:
      - selenoid
    volumes:
      - "./:/etc/selenoid"
      - "./target:/output"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./target:/opt/selenoid/video"
    environment:
      - "OVERRIDE_VIDEO_OUTPUT_DIR=$PWD/target"
    command: [ "-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-container-network", "selenoid" ]

  selenoid-ui:
    image: "aerokube/selenoid-ui:latest"
    container_name: selenoid-ui
    links:
      - selenoid
    ports:
      - "8083:8080"
    networks:
      - selenoid
    command: [ "--selenoid-uri", "http://selenoid:4444" ]

networks:
  selenoid:
  jbrs_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1