version: "3.2"

services:

  tc-server: ### the main tc-server (aka SUT)
    image: jetbrains/teamcity-server:latest
    container_name: teamcity-server-instance
    ports:
      - "8111:8111"
    volumes:
      - ./teamcity_server/datadir:/data/teamcity_server/datadir
      - ./teamcity_server/logs:/opt/teamcity/logs

  agent1: ### this agent exists as authorized one
    image: jetbrains/teamcity-agent:latest
    privileged: true
    container_name: teamcity-agent1-instance
    volumes:
      - ./teamcity_agent/agent1/conf:/data/teamcity_agent/conf
    links:
      - tc-server
    environment:
      - SERVER_URL=teamcity-server-instance:8111
      - AGENT_NAME=teamcity-agent1
      - DOCKER_IN_DOCKER=start

#  ngrok: ### the service provides an external tunnel to the localhost
#    image: ngrok/ngrok:latest
#    restart: unless-stopped
#    command: [ "start", "--all", "--config", "/etc/ngrok.yml" ]
#    volumes:
#      - ./ngrok.yml:/etc/ngrok.yml
#    ports:
#      - "4040:4040"

  selenoid: ### the service provides remote run of web driver instances and more
    image: "aerokube/selenoid:latest"
    container_name: selenoid
    ports:
      - "4444:4444"
    networks:
      - selenoid
    volumes:
      - ./:/etc/selenoid
      - ./target:/output
      - ./target:/opt/selenoid/video/
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=$pwd/target
    command: [ "-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video/", "-container-network", "selenoid" ]

  selenoid-ui: ### UI for the selenoid server
    image: "aerokube/selenoid-ui:latest"
    container_name: selenoid-ui
    links:
      - selenoid
    ports:
      - "8083:8080"
    networks:
      - selenoid
    command: [ "--selenoid-uri", "http://selenoid:4444" ]

  chrome_114.0:
    image: "selenoid/chrome:114.0"
    container_name: chrome_114.0
    networks:
      - selenoid
    links:
      - selenoid
      - selenoid-ui
    depends_on:
      - selenoid
      - selenoid-ui
    volumes:
      - /dev/shm:/dev/shm

  firefox_115.0:
    image: "selenoid/firefox:115.0"
    container_name: firefox_115.0
    networks:
      - selenoid
    links:
      - selenoid
      - selenoid-ui
    depends_on:
      - selenoid
      - selenoid-ui

  edge_114.0:
    image: "browsers/edge:114.0"
    container_name: edge_114.0
    networks:
      - selenoid
    links:
      - selenoid
      - selenoid-ui
    depends_on:
      - selenoid
      - selenoid-ui

  safari_15.0:
    image: "browsers/safari:15.0"
    container_name: safari_15.0
    networks:
      - selenoid
    links:
      - selenoid
      - selenoid-ui
    depends_on:
      - selenoid
      - selenoid-ui

networks:
  selenoid:
    external: true