spring:
  main:
    banner-mode: off

core:
  browser:
    headless: "true"
    timeout: 40000
    remote:
      active: "true"
      url: "http://localhost:4444/wd/hub"
      video-recording: "false"
  allure:
    page-source: "false"
    browser-logs: "false"

tc:
  server:
    url: "http://host.docker.internal:8111"
    token: "" ### Super user's token. Should be stored from teamcity-server/logs/'teamcity-server.log' file
    api:
      host: "localhost:8111"

  users:
    - username: "admin" ### Admin user (should be created manually during the server's first run
      password: "admin"

    - username: "" ### Super user
      password: "${tc.server.token}"

  vcs:
    - type: "GIT" ### The test GIT repository properties
      rootUrl: "https://github.com/Grendelius/"
      project: "sandbox"
      username: "atolkachev"
      password: ""