version: "3.2"

services:

  tc-server:
    image: jetbrains/teamcity-server:latest
    container_name: teamcity-server-instance
    ports:
      - "8111:8111"
    networks:
      jbrs_net:
        ipv4_address: 10.5.0.5
    volumes:
      - ./teamcity_server/datadir:/data/teamcity_server/datadir
      - ./teamcity_server/logs:/opt/teamcity/logs
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "4g"

  agent:
    image: jetbrains/teamcity-agent:latest
    container_name: teamcity-agent-instance
    volumes:
      - ./teamcity_agent/agent/conf:/data/teamcity_agent/conf
    environment:
      - SERVER_URL=http://10.5.0.5:8111
      - TEAMCITY_SERVER_MEM_OPTS=-Xmx4g --XX:ReservedCodeCacheSize=1g

networks:
  jbrs_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1